### ISSUE TITLE
API timeout in Firmware 041.0 auf Hardware Version v2

### ISSUE THREAD

**Issue by fisihh** [goecharger/go-eCharger-API-v1#111]
Anscheinend seit FW 041.0 für Hardware Version v2 läuft die API nicht mehr stabil.

Ich nutze ein python Script welches via requests post den Ladestrom dynamisch steuert (http://xxx.xxx.xxx.xxx/mqtt?payload=amp=<wert>), zudem hole ich mir per requests den status via http://xxx.xxx.xxx.xxx/status ....

Bisher lief das fast 2 Jahre stabil. Seit ein paar Tagen reagiert die API nicht mehr auf die Anfragen / Änderungen und es kommt zu einem timeout. Der Ladevorgang läuft ganz normal weiter ...

Setze ich die Wallbox stromlos und starte sie dadurch neu, ist die API kurzfristig erreichbar und lässt sich steuern. Wenn dann aber die dynamische Regelung startet, nimmt sie quasi keine Änderungen mehr entgegen.

**Comment by fuchs-1978** [comment]
Du nutzt wirklich amp und nicht amx? Dann hast du ziemlich vielen Werte in die Box geschrieben. Vielleicht hat der eEProm jetzt ein Problem

**Comment by fisihh** [comment]
Die API (vermute mal in der v2 Hardware) kennt nur amp, hier mal ein Auszug von status:

{"version":"B","tme":"2810221425","rbc":"58","rbt":"9412539","car":"1","amp":"6","err":"0","ast":"3","alw":"0","stp":"0","cbl":"32","pha":"56","tmp":"24","dws":"0","dwo":"0","adi":"0","uby":"0","eto":"32930","wst":"3","txi":"0","nrg":[218,218,218,1,0,0,0,0,0,0,0,0,0,0,0,0],"fwv":"041.0","sse":"006924","wss":" ……….

**Comment by fuchs-1978** [comment]
Doch, setzten musst du mit AMX, der Rückwert ist dann AMP

**Comment by fuchs-1978** [comment]
AMX ohne eEProm, AMP mit eEProm schreiben

**Comment by fisihh** [comment]
Läuft alles wieder stabil. Danke für den nicht unerheblichen Tipp mit dem “Software Schalter amx”. In der API Doku ist nun ja auch der Unterschied zwischen “amp” und “amx” gut beschrieben.

**Comment by fisihh** [comment]
Ich schließe denn issue
