### ISSUE TITLE
API v1 Param "cch" & "cfi" writes in "cid"

### ISSUE THREAD

**Issue by 8mk** [goecharger/go-eCharger-API-v1#117]
Hi, 
when you try to write in `http://server/mqtt?payload=cch=0` it writes the value into `cid`. Same in situation is with `cfi`.

This occur starting version 042 until 055.5 

Kind regards
Marcus

**Comment by didi-j** [comment]
still not working in 055.7

**Comment by 0xFEEDC0DE64** [comment]
Thank you all for reporting this issue, it could be reproduced and fixed, the next firmware release will include a fix for this!

**Comment by didi-j** [comment]
working with 56.1
thanks
