### ISSUE TITLE
amx/amp höhere Auflösung

### ISSUE THREAD

**Issue by jsphuebner** [goecharger/go-eCharger-API-v1#119]
Wir nutzen derzeit eine Heidelberg Energy Control. Hier lässt sich der Ladestrom auf 0,1A genau festlegen. Das ist für die PV Regelung sehr vorteilhaft, da es kleinere Leistungssprünge produziert.

Wegen der 442 Förderung wollen wir auf einen go-e umrüsten.

Ist für den go-e Charger auch eine höhere Auflösung angedacht?

**Comment by erxbout** [comment]
Das wäre technisch machbar ab hardware V3 aber derzeit nicht angedacht
