### ISSUE TITLE
Go-E Charger  V2+ EVCC + Dacia Spring

### ISSUE THREAD

**Issue by gaborgast** [goecharger/go-eCharger-API-v1#120]
I own a go-e charger V2 and would like to run pv surplus charging via evcc with my dacia spring.
unfortunately the dacia switches into sleep in a charge pause.
Is their a way to emulate the "simulateUnplugging" of the V3 go e charger?
Should be possible since it is just a software freatures?

**Comment by erxbout** [comment]
Is this still a problem?

If so then I can say that "simulateUnplugging" can not be fixed by software..
A new charger can support that and 1/3 phase change..
