### ISSUE TITLE
Bitte neues Feature amx dokumentieren

### ISSUE THREAD

**Issue by Clemens-XXX** [goecharger/go-eCharger-API-v1#14]
Liebes Go-eCharger Team,

im Loxone-Wiki habe ich gelernt, dass es einen neuen Befehl amx gibt.  Dieser setzt den Ladestrom auf den angegebenen Wert, ohne dass dieser permanent im EEPROM gespeichert wird.

Könnte Ihr das bitte entsprechend dokumentieren? Etwa welcher Wertebereich erlaubt ist (z.B. wenn der Stromzähler Werte  gegen Null oder negativ (Netzbezug) liefert)  und welche Frequenz der Werteänderung zu empfehlen ist.

Danke!

**Comment by peterpoetzi** [comment]
Danke ist passiert. Generell empfehle ich 5 Sekunden für jegliche Regelung. Erlaubt ist das gleiche wie bei amp. Es verhält sich exakt so, als würde man amp= setzen, den Unterschied merkt man erst bei nächsten reboot, da wird amp wieder auf den letzten mit amp geschrieben Wert zurückgesetzt.
