### ISSUE TITLE
Where is the value of tmp measured?

### ISSUE THREAD

**Issue by klacol** [goecharger/go-eCharger-API-v1#15]
I have integrated our go-eCharger with this great [integration](https://github.com/cathiele/homeassistant-goecharger) into [Home-Assistant](https://www.home-assistant.io). 

The payload of the API deliveres the value of the field `tmp`. This is defined in the documentation as:

> Temperature of the controller in °C

Today the value shows 4-6 °C. I am wondering where this tempature is measured, since my go-eCharger is mounted in my cellar room (in the heating room). The room is not so cold. The cable is plugged in and the main part of the cable is placed outside. Is it possible, that the temperature is measured somewhere in the cable?

**Comment by klacol** [comment]
The value of the temperature is measured between 3 to 6 °C, which seem to bee reasonable for outside temperature today (Western Germany in December).

![image](https://user-images.githubusercontent.com/10479772/101279282-7967e580-37c1-11eb-9a20-a27cd9ce1e57.png)

**Comment by peterpoetzi** [comment]
This is the data from the temperatur sensor on the microcontroller's silicon die, which is not well calibrated and can be off by multiple counts. Maybe, you also have the tma field in the status object, which contains more accurate temperature readings (only available for newer charging stations)

**Comment by klacol** [comment]
Ok, thanks for the clarification. No, the charging station is from the beginning of 2019 and has no `tma `field.

**Comment by klacol** [comment]
see also the issue #6.
