### ISSUE TITLE
Modbus Register doppelt

### ISSUE THREAD

**Issue by edgale** [goecharger/go-eCharger-API-v1#17]
Hallo,
das Modbus Register 315 ist in der Doku 2 mal vergeben.
Rückt alles einfach eine Adresse nach hinten?

https://github.com/goecharger/go-eCharger-API-v1/blame/master/go-eCharger%20Modbus%20TCP%20API%20v1%20DE.md#L79

**Comment by edgale** [comment]
Und Register ```126``` ist als ```Input Register``` in ```4. Registertypen```  angegeben, taucht aber nicht als Regsiter in ```3. Modbus Register``` auf. Auserdem fehlt Regster ```120``` in ```4. Registertypen```

**Comment by rootandy** [comment]
Hallo,

so die meisten Punkte sind jetzt soweit alle behoben.

**Comment by edgale** [comment]
Hallo,

danke für die Änderungen.
Das Register 315 is allerdings in der Doku immer noch doppelt belegt.
![Screenshot from 2021-01-04 07-18-30](https://user-images.githubusercontent.com/4374065/103506510-2daa6980-4e5d-11eb-9d70-65b01f048d62.png)
