### ISSUE TITLE
TXI without description

### ISSUE THREAD

**Issue by MK-2001** [goecharger/go-eCharger-API-v1#2]
Hallo Peter, 

ich habe für die Home Automation einen Adapter erstellt und bin darauf gestoßen, dass mir ein Attribut "TXI" übermittelt wird. Hierzu habe ich aber keine Informationen gefunden. 

https://github.com/MK-2001/ioBroker.go-e/issues/5

Verrätst du mir was damit gemeint ist?

Noch eine weitere Frage: Mir würde es etwas bringen, wenn die Dokumentation als Manual.md "Markdown" Dokument zur verfügung steht. Kann ich diese für dich konvertieren und als Pol-Request einstellen? Oder lehnst du die Doku als Markdown generell ab? Dann mache ich mir die Mühe nicht. ;-) 

Gruß
Marcus

**Comment by hofster** [comment]
Ich kann dir zumindest sagen, dass TXI für "transmit interface" steht.
