### ISSUE TITLE
Nachkommastellen bei AMP und AMX möglich?

### ISSUE THREAD

**Issue by fuchs-1978** [goecharger/go-eCharger-API-v1#23]
Ist es möglich die beiden Werte mit einer Nachkommastelle zu versehen um die Leistungsanpassung noch genauer vorzunehmen?

**Comment by peterpoetzi** [comment]
Hi, das ist leider nicht möglich weil Autos den Strom nur in ganzen Ampere auswerten, außerdem kann der interne Charge Controller nur mit ganzen Werten umgehen

**Comment by fuchs-1978** [comment]
Ah okay, vielen Dank für die Info
