### ISSUE TITLE
Wie kann ich die Box über den API neustarten?

### ISSUE THREAD

**Issue by faxmaster** [goecharger/go-eCharger-API-v1#31]
Da es in der App möglich ist, gibt es sicher diese Funktion. Diese ist leider nicht dokumentiert.
Gibt es ein API call,  mit dem man über den API die Box neustarten kann?

**Comment by peterpoetzi** [comment]
Mit rst=1

**Comment by faxmaster** [comment]
Viel zu Einfach! Besten Dank für die schnelle Antwort!

**Comment by fuchs-1978** [comment]
Kommt dieser Befehl noch mit in die API Dokumentation
