### ISSUE TITLE
Writing MQTT value locally

### ISSUE THREAD

**Issue by torebrigaglia** [goecharger/go-eCharger-API-v1#35]
Hi Thank you for this charger, it was missing in the market.
it seems i can only set values on the charger with modbus or http://x.x.x.x/mqtt?payload=
i am trying to publish a value to be set using this topic:  "go-eCharger/serialnumber/cmd" or "go-eCharger/serialnumber/cmd/req" publishing a json formatted message like {"amp":"10"}  but it has no effect. 
Please advice

**Comment by erikderzweite** [comment]
Neither does escaping work, nor "amp=10" or similar. An example in the documentation would be nice.

**Comment by erikderzweite** [comment]
You need to provide the command in the same format as with modbus or REST api, e.g. "amx=10"

**Comment by erxbout** [comment]
Exactly.. In the API V1 this is not handled by json input
