### ISSUE TITLE
cURL: Operation timed out 

### ISSUE THREAD

**Issue by kaufi88** [goecharger/go-eCharger-API-v1#50]
Hi there,
we've three go-e charger for our students home.
To manage the wallboxes and charging activity we poll each wallbox every 5 minutes with cURL.

In some cases (about 2 of 5 times) we get an Operation timed out error.
URL:http://192.168.50.13/statusError:Operation timed out after 4062 milliseconds with 948 out of 1145 bytes received
URL:http://192.168.50.14/statusError:Operation timed out after 5000 milliseconds with 0 bytes received

Why does the wallbox stop transfering data?
How can this be fixed?

Thanks
Daniel

**Comment by peterpoetzi** [comment]
I can confirm that the cloud service is overloaded at the moment. We are actively working on a new cloud service which will go live in the next weeks and will have a much higher capacity and no rate limiting / fair use policies.

**Comment by kaufi88** [comment]
Thanks for the fast response.
As you can see from the IP, we use a the local API for polling the wallbox.
Does the slow cloud has an impact to the local API?

**Comment by peterpoetzi** [comment]
Sorry, I did not look at that. The local API should not be affected by the cloud. Maybe the WiFi signal strength is too low. You can also try restarting the charger.

**Comment by kaufi88** [comment]
Oh well, the WiFi of the box is really bad. I miss the RJ-45 jack.
Is there a way to check the wifi singal from the perspective of the wallbox?

(Yes, I already restarted the boxes...)

**Comment by peterpoetzi** [comment]
I do not have any solution but a WiFi repeater at the moment. However it might be possible to make the connection better with a future firmware update, we are looking into that at the moment.

**Comment by kaufi88** [comment]
Okay thanks. I'll try to get the accesspoint closer to the wallboxes and keep this topic updated when I've improved the WiFi signal.
