### ISSUE TITLE
Ist Eigenverbruach der Box in 'eto' enthalten?

### ISSUE THREAD

**Issue by mat-fu** [goecharger/go-eCharger-API-v1#52]
Mich würde interessieren, ob der Eigenverbruach der Box in dem Parameter 'eto' enthalten ist, oder hier nur die abgegeben Energiemenge aufgeführt ist?
Hintergrund der Frage ist, dass Ich Abweichungen zwischen der App des Fahrzeuges und 'eto' feststelle.

Vielen Dank für eine Antwort

**Comment by peterpoetzi** [comment]
eto wird immer nur bei ganze kWh geschrieben, wenn man den go-eCharger oft aussteckt, kann es sein dass etwas verloren geht. Der Eigenverbrauch der Ladebox ist ca. 3W (je nach LED Farbe) und wird, insbesondere wenn nicht geladen wird, nicht mitgezählt.

**Comment by mat-fu** [comment]
Vielen Dank für die schnelle Antwort @peterpoetzi !
