### ISSUE TITLE
API V1 mit Hardware V3

### ISSUE THREAD

**Issue by chk2902** [goecharger/go-eCharger-API-v1#57]
verzögerte Ausgabe des "amx"-Registers

17:08:21.169: http://.../status
17:08:22.233: "car":"2","amx":"6","amp":"6","err":"0","ast":"0","alw":"1"
17:08:22.388: http://.../mqtt?payload=amx=13
17:08:23.591: "car":"2","amx":"6","amp":"13","err":"0","ast":"0","alw":"1"
17:08:24.620: http://.../status
17:08:25.112: "car":"2","amx":"13","amp":"13","err":"0","ast":"0","alw":"1"

Auch ist die Antwortzeit der Wallbox relativ lang, allerdings gibt es hier beim Log 2 Apps gleichzeitig, die die Wallbox abfragen - die von go-e und meine.

**Comment by sebnaf** [comment]
Ja, und ein weiteres Problem, zB:

http://.../mqtt?payload=alw=1 gibt in der JSON-Response noch den vorherigen, alten Wert zurück.
Das soll bitte behoben werden.

**Comment by sebnaf** [comment]
Unsere Tests haben ergeben, dass die Änderung erst nach 7 Sekunden ersichtlich ist.

**Comment by peterpoetzi** [comment]
Mit V3 Firmware 051.3 und höher werden gesetzte Parameter schneller übernommen

**Comment by chk2902** [comment]
(das war die SW 51.4...)
