### ISSUE TITLE
KfW-Förderung: Wallbox mit Limit 11 kW gibt zu hohen Maximalstromwert zurück

### ISSUE THREAD

**Issue by chk2902** [goecharger/go-eCharger-API-v1#60]
... in "ama" wird 32 zurückgegeben.

Das ist für mich nicht konsistent, die Wallbox lädt nur bis 16A, egal was bei "amx" vorgegeben wird.

**Comment by peterpoetzi** [comment]
Zusätzlich zum ama Wert muss man auch den adi Wert beachten. Wenn der 1 ist, ist der Maximalstrom, unabhängig von den sonstigen Einstellungen maximal 16A.

Leider ist es derzeit nicht möglich zu verhindern dass der ama Wert auf bis zu 32A gestellt wird, das macht allerdings in der Praxis keinen Unterschied da eh die Limitation durch adi kommt.
