### ISSUE TITLE
check if new firmware available

### ISSUE THREAD

**Issue by clyso** [goecharger/go-eCharger-API-v1#63]
is there any possibility to check for new firmware updates besides using the official app while connected via cloud?
I would like to implement a check in my home assistant that i get notified when a new update for the charger is available.

**Comment by sigma415** [comment]
I also would really appreciate such a firmware check feature. I hab to downgrade on V033 (HW V2) because 040 killed the restart function of my box. And iOS app only tells me, that there is some new FW version available, but not which one .... :(

**Comment by peterpoetzi** [comment]
The restart function is fixed with V2 Firmware 041

**Comment by peterpoetzi** [comment]
The V2 does not know the newest firmware as an API parameter, but you can read it in the changelog in the app
