### ISSUE TITLE
How to switch between 1 and 3 phases

### ISSUE THREAD

**Issue by povlhp** [goecharger/go-eCharger-API-v1#67]
Can't see how to switch between 3 and 1 phase charging.
Docs on how to set values says name of method is SET. That method does not exist in HTTP. It is likely a type and thus GET. Other options would be PUT/POST

**Comment by ddrrhh** [comment]
See issue #66

**Comment by 0xFEEDC0DE64** [comment]
the http api v1 does not support switching 1/3 phase charging
