### ISSUE TITLE
MQTT verbessern?

### ISSUE THREAD

**Issue by Clemens-XXX** [goecharger/go-eCharger-API-v1#7]
Schaue mir gerade Optionen für den lokalen MQTT an (geniales Feature!)

Ich sehe keinen Sinn darin, bei MQTT parallel zu Übermittlung der Einzelwerte noch einmal alle Werte als Array zu senden. Konkret: go-eCharger/XXXX/status. Zumindest hier zerhaut mir das die Anzeigen. Vielleicht seht Ihr das auch so und könnt das abschalten?

**Comment by peterpoetzi** [comment]
Der go-eCharger sendet über MQTT eigentlich jeden Wert nur einmal, eventuell ist das ein Anzeigeproblem beim MQTT Client? Wie sieht denn die Anzeige aus?

**Comment by Clemens-XXX** [comment]
![Bildschirmfoto](https://user-images.githubusercontent.com/71373483/95057970-273e1180-06f7-11eb-8127-ffcba5b082cd.png)
So stellt sich das bei mir im MQTT Broker dar. Erst ein Array ähnlich wie bei JSON und dann alle Werte einzeln. (Loxberry mit MQTT Plugin zu Anbindung an Loxone Hausautomatisierung).

**Comment by peterpoetzi** [comment]
Diese einzelnen Topics kommen nicht vom go-eCharger, sondern werden wohl von MQTT Broker angelegt um das JSON Objekt aufzusplitten

**Comment by Clemens-XXX** [comment]
Hm, also andere MQTT-Quellen machen das nicht. Und ich habe einige eingebunden ....
