### ISSUE TITLE
Temeraturen in V3 Firmware 51

### ISSUE THREAD

**Issue by man10to** [goecharger/go-eCharger-API-v1#74]
Hallo,
bisher lese ich die temperaturen mit iobroker aus (einfach eine der vier und gut ist)
nun sind die ja leer und es werden in all temperatures (tma) ja zwei in einem Array ausgegeben.
Wie kann man das mit IObroker lösen ?
Warum sind die andern vier leer ?
Werden die mal wieder gefüllt ?

**Comment by peterpoetzi** [comment]
Die V3 hat nur mehr 2 Temperatursensoren

**Comment by man10to** [comment]
Hallo,
Ja das ist ja klar. 
Aber wie kann ich die auslesen ?
Mit dem iobroker ?

**Comment by 0xFEEDC0DE64** [comment]
mit dem api key "tma" können die Temperaturen ausgelesen werden
