### ISSUE TITLE
JSON Response does not reflect changed value (and updates are slooooooow...)

### ISSUE THREAD

**Issue by sebnaf** [goecharger/go-eCharger-API-v1#75]
Hardware: V3

Changing a value like `http://.../mqtt?payload=alw=1`does still return the old, original value in the JSON Response.
The changed value is only available in /status after 4-6s, which is something we cannot work with.

I'd expect
- the JSON response to reflect the changed value instantly
- the /status endpoint to reflect the correct value shorty after the change, not after several seconds.

Thank you

**Comment by sebnaf** [comment]
according to the documentation, this really seems to be a bug.

4. Rückgabewerte :
Lokales WLAN / Hotspot
Verbindung	Rückgabe
WLAN Hotspot	Komplettes status JSON Objekt mit bereits geänderten Wert
WLAN lokales
Netzwerk	**Komplettes status JSON Objekt mit bereits geänderten Wert**
Bei jedem Status Request und jedem Kommando wird das Status JSON-Objekt
zurückgegeben. Ein nicht erfolgreiches Kommando erkennt man daran dass sich der Wert im
Status Objekt nicht geändert hat.

**Comment by sebnaf** [comment]
Any remarks here? Thank you

**Comment by amnesia106** [comment]
+1

**Comment by bacanol** [comment]
+1

**Comment by Sillium007** [comment]
+1

**Comment by Kanonkop** [comment]
+1

**Comment by Optic00** [comment]
+1 just ordered a v3 for a relative

**Comment by peterpoetzi** [comment]
This bug is fixed internally, we will release an firmware update very soon

**Comment by sebnaf** [comment]
Excellent news, thank you @peterpoetzi!

**Comment by amnesia106** [comment]
![photo_2021-09-05_18-28-40](https://user-images.githubusercontent.com/40226796/132134208-90c2a51e-ffa0-4422-b358-4362d8049d2e.jpg)

**Comment by sebnaf** [comment]
@peterpoetzi Ich lasst hier einen Response 13s warten - das ist doch nicht wirklich elegant… Könnt ihr da bitte nochmals nachbessern?

 sna@arbeitsgeraet  ~  time curl 'http://10.10.20.22/mqtt?payload=alw=1'

{"version":"B", ... ,"loa":0,"lch":507}
curl 'http://10.10.20.22/mqtt?payload=alw=1'  
0.00s user 0.00s system 0% cpu 13.417 total

**Comment by sebnaf** [comment]
@peterpoetzi Falls dieses Problem mit der API v2 nicht bestehen sollte, bitte ich umgehend um die Dokumentation, damit wir das umbauen können. Die 13s Wartezeit sind architektonisch noch schlimmer als der Fehler an sich.

**Comment by CHulkW** [comment]
+1

Da konnte ich eher mit dem Fehler leben, als mit der langen Wartezeit. So ist das leider wirklich nicht gut nutzbar.

**Comment by sebnaf** [comment]
Die ersten User melden einen Timeout. 
Es wäre wirklich gut zu wissen, ob das mit der API v2 besser funktioniert. Hat irgendjemand Zugang dazu oder kann sich @peterpoetzi bitte dazu äussern? Danke

**Comment by chilobo** [comment]
Auch bei mir wird die GO-E unter openhab nicht mehr initialisiert:
`Total timeout 5000 ms elapsed`
IP/status und IP/api/status liefern im Browser noch Daten, dauert ca. 7 s

**Comment by peterpoetzi** [comment]
Ich kann bestätigen dass bei manchen Usern die v1 API jetzt mehrere Sekunden zum Antworten braucht. Wir arbeiten hier an einem Bugfix

**Comment by sebnaf** [comment]
@peterpoetzi Danke. Da nun doch einige Implementationen seitdem ein Timeout liefern - mit welchem Zeithorizont dürfen wir hier rechnen?

**Comment by chilobo** [comment]
In Openhab habe ich die timeouts beim Lesen und Senden auf 10 s hochgesetzt. Jetzt klappt die Steuerung wieder.

**Comment by sebnaf** [comment]
@chilobo Das wird wahrscheinlich nur mittelfristig etwas bringen, da das Timeout länger wird, je länger die Uptime ist. 
Hoffen wir auf einen baldigen Fix.

**Comment by chilobo** [comment]
Scheint zu stimmen. Warum wird das Timeout länger? 
Macht es dann Sinn:
- die Box ab und an im Sicherungskasten stromlos zu machen
- die Ladung neu zu starten 
- oder reicht es, die Box aus- und wieder anzuschalten? 

Habe gerade mal Letzteres probiert, scheint nicht sicher zu helfen.

**Comment by sebnaf** [comment]
Hallo @peterpoetzi, könnten wir bitte eine Aussage betreffend Zeithorizont Bugfix bekommen? Danke

**Comment by peterpoetzi** [comment]
Es handelt sich hier um eine Thread-Locking Problem, das bereits intern gelöst und und gerade getestet wird. Ein Update erwarte ich für heute 09.09

**Comment by sebnaf** [comment]
Danke für das Update. Das sind sehr erfreuliche News. Danke, dass ihr so schnell seid.
