### ISSUE TITLE
Unable to set MQTT URL (Hardware v3)

### ISSUE THREAD

**Issue by eicosan** [goecharger/go-eCharger-API-v1#77]
After activating the option "Aktiviere MQTT API" I can change the URL below, but after saving the configuration it returns to the default one: mqtt://test.mosquitto.org:1883.

**Comment by DaveMe81** [comment]
Same here! I was hoping that this is already known an to be fixed soon.

**Comment by sebnaf** [comment]
Same behaviour here as well.

**Comment by Marv2190** [comment]
Tested, just now and works for me.

**Comment by eicosan** [comment]
I just figured out that setting the MQTT server is possible using the new REST API:
http://##GO-E_IP##/api/set?mcu="mqtt://##MQTT_HOST##:1833"

**Comment by EugenGanshorn** [comment]
I can confirm, there are no status updates published to the topic "go-eCharger/##SERIAL_NR##/status"

is this intentional, or when will it be fixed?

**Comment by peterpoetzi** [comment]
The V3 has a slightly different MQTT protocol which sends all API parameter to separate topics: 
https://github.com/goecharger/go-eCharger-API-v2
