### ISSUE TITLE
V3 - FW51.1 - Modbus Register 299

### ISSUE THREAD

**Issue by JoGi65** [goecharger/go-eCharger-API-v1#79]
Hallo,

ist es normal, wenn man per Modbus Register 299 schreibt, dass sich Register 300 immer mitverändert?

EDIT:
Vielleicht noch zur Info:
Wenn man das Register 299 schreibt, bleibt der Wert auch nach an- und abstecken des Chargers erhalten, was schon stark darauf hindeutet, das Register 300 tatsächlich immer parallel beschrieben wird.

Sollte sich die Anzahl der Schreibvorgänge noch immer auf ca. 100.000 beschränken, wäre eine Info schon angebracht, da ich dann den Regelalgorithmus für das PV geführte Laden entsprechend einbremsen muss.

LG Johannes

**Comment by Sillium007** [comment]
Das wäre durchaus bedenklich. Klingt aber schon sehr danach wenn der Wert nach dem Ausschalten des Chargers beim nächsten Start immer noch da ist.

**Comment by JoGi65** [comment]
Ich habe vor einigen Tagen auf meine Email Anfrage eine Antwort erhalten.

**Zitat gekürzt:**
_Sehr geehrter Herr 

ich habe nun eine Rückmeldung aus unserer Entwicklung erhalten. 
Ihr Charger entspricht der neuesten Generation, weshalb die Beschränkung von ca. 100.000 Schreibvorgängen nicht mehr aktuell ist. 
Die neue Generation kann (quasi) unlimitiert oft schreiben und persistiert daher den Strom immer - das ist also ein gewolltes Verhalten._ 

Ich hoffe das dem so ist, auch wenn es für mich etwas merkwürdig ist, da sich 300 ja praktisch erübrigt.
