### ISSUE TITLE
Why to send WLAN Name und Password on Cloud?

### ISSUE THREAD

**Issue by Clemens-XXX** [goecharger/go-eCharger-API-v1#8]
Die API sendet die Zugangsdaten für WLAN an die Cloud sowie per JSON und MQTT. Sehe keinen Nutzen darin. Vielleicht aus Sicherheitsgründen besser abschalten?

**Comment by peterpoetzi** [comment]
Es wird nur der WLAN Name in die Cloud geschickt damit in der app angezeigt werden kann, mit welchem WLAN man verbunden sit. Das Passwort jedoch nicht.
