### ISSUE TITLE
go-e.0 	error	self signed certificate

### ISSUE THREAD

**Issue by Proestkh** [goecharger/go-eCharger-API-v1#80]
Bekomme bei jeder Aktualisierung o.g. Fehlermeldung.
Weiss jemand was zu tun ist?

Node.js = v12.22.1
NPM = 6.14.12
Go-eCharger Adapter = 1.0.15

**Comment by peterpoetzi** [comment]
Um welche API Schnittstelle geht es hier?

**Comment by Proestkh** [comment]
![Go-e API](https://user-images.githubusercontent.com/81586977/129774513-eb9d4df8-a32c-4917-9737-0364fe2112bb.jpeg)

**Comment by peterpoetzi** [comment]
Ok aber wo ist die Fehlermeldung?

**Comment by Proestkh** [comment]
Alle 30 Sekunden im LOG, Text wie im Betreff.

Von meinem iPhone gesendet

**Comment by peterpoetzi** [comment]
Geht es um diesen iobroker Adapter https://github.com/MK-2001/ioBroker.go-e/issues/?

**Comment by Proestkh** [comment]
Ja, MK-2001 Version 1.0.15

Von meinem iPhone gesendet

**Comment by peterpoetzi** [comment]
Dann bitte im https://github.com/MK-2001/ioBroker.go-e/issues/ einen Bug eröffnen
