### ISSUE TITLE
no new values in cloud api

### ISSUE THREAD

**Issue by Danny-clever-pv** [goecharger/go-eCharger-API-v1#81]
Hello, I got since yesterday no new data from api_status endpoint:
{"success":true,"age":77254979,"data":{"version":"B","tme":"**1808212120**","rbc":"39","rbt":"2753054","car":"4",....

FW: 041.0

sending commands is not a problem, the connection to the internet seems not the problem.
can someone confirm this?
I try on/off and rest.
Some other ideas?

Best regards, Danny

**Comment by BrianEstrada** [comment]
I'm having the same issue right now, works fine on rabbitMQTT but not via the cloud API

**Comment by peterpoetzi** [comment]
Not it should work again

**Comment by Danny-clever-pv** [comment]
Yes it works thank you!
