### ISSUE TITLE
Charger V2 stürzt weiterhin ab! 🤷🏻‍♂️

### ISSUE THREAD

**Issue by kaeferfreund** [goecharger/go-eCharger-API-v1#89]
Hallo zusammen,

meine beiden am häufigsten genutzten go-e V2 stürzen auch mit der "neuen" 041.0 Firmware ab. Diesmal sogar schlimmer als vorher (vorher hat der Charger in 5/10 Fällen wenigstens weiter geladen):

Der Charger fängt an zu laden, läd wenige Sekunden, dann wird plötzlich mehrfach die Kabel-Verriegelung betätigt im Charger während die LEDs vom Charger und das Auto einen Ladevorgang signalisieren. In der App wird erst der korrekte, dann plötzlich ein sehr geringer Ladestrom bis runter auf 10W angezeigt, geht dann wieder hoch auf den Zielwert, wieder runter bis das Auto dann keine Lust mehr hat und in den Fehlerzustand geht.

Das Spiel ließ sich mit 2x MiniCooper SE und 1x ID4 beliebig oft wiederholen. Ein Neustart in der App hat das Problem ebenfalls nicht behoben.

Alle Autos laden an meinen V3 Boxen, einen Parkplatz weiter einwandfrei.

Nach dem ich die beiden V2 Boxen für 10 Sekunden vom Strom getrennt habe hat der Mini SE einwandfrei geladen.

@peterpoetzi @0xFEEDC0DE64

Wann kann ich mich darauf verlassen, dass ich mit den go-e Produkten einwandfrei laden kann?

Edit: **Das Problem trat mit BEIDEN V2 Chargern vollständig gleich auf**. Beide Charger haben kurz nacheinander das Update auf die 041.0 Firmware erhalten und werden über den gleichen Lasttrenner eingeschaltet. Deswegen hatte ich erst das Fahrzeug im Verdacht, aber alle Fahrzeuge hatten den gleichen Fehler an beiden V2 Boxen, an den V3 Boxen wurde anstandslos geladen.

**Comment by fuchs-1978** [comment]
Ich habe dreimal die gleiche Version mit gleicher Software. Mit einem Mii und einem EQV noch nie Probleme gehabt.

**Comment by kaeferfreund** [comment]
Die gleiche Version heißt das Modell vom Typ go-e V2?

**Comment by fuchs-1978** [comment]
Genau, die V2 ohne die Phasenumschaltung. Ebenfalls mit der 41er Version. Läuft perfekt im PV Überschuss, es wird also mehrmals über alw das Laden ein und ausgeschaltet. Über AMP setze ich die Ströme

**Comment by kaeferfreund** [comment]
Ja! Jedes Auto mit dem Kabel das ab Werk geliefert wurde. Also 3 verschiedene Fahrzeuge mit 3 verschiedenen Kabeln probiert.

Nochmal: Das Problem ist nicht mit einem Fahrzeug (und Kabel) Wechsel verschwunden. Nicht mit einem Neustart durch die App sonder NUR nach dem stromlos Schalten.

@fuchs-1978 Ich würde mich nicht wundern, wenn das Problem bei Dir auch noch auftritt, so war es in der vorherigen Firmware auch. Da haben anfangs noch Leute groß erzählt "bei mir tritt das Problem nicht auf". Am Ende waren alle Wallboxen betroffen meinem Bekanntenkreis und das sind dank KFW Förderung nicht wenige. Viele haben es lange nicht gemerkt, weil Sie kein E-Auto hatten oder dachten, dass das periodische Leuchten (Neustart...) gewollt sei...

**Comment by fuchs-1978** [comment]
Aber ich habe ja die gleiche Hardware wie du. V2 mit der 41 Version. Und habe zwei Autos an den drei Boxen. Läuft problemlos

**Comment by kaeferfreund** [comment]
Ich wünsche jeden, dass das so bleibt. Aber meine Erfahrung hier sagt ganz klar: abwarten, so lange gibts die 041.0 ja noch nicht und bei mir lief Sie ja schon vor der offiziellen Verteilung, weil meine V2 Boxen mit der Vorgänger FW unglaublich viele Abstürze hatten... (die V3 Boxen haben ebenfalls noch viele, viele Bugs...)

**Comment by chilobo** [comment]
Ich hatte 2 Monate lang die V2 und dann die V3. Keine Abstürze mit Ioniq und e-up (2018). Beim e-up muss man immer zwei Mal anstecken und er wacht nicht mehr auf, wenn man die Box länger als 20 s ausgeschaltet hat bzw. sie beim PV-gesteuerten Laden abschaltet oder den Strom auf < 6 A stellt. Beim Ioniq keine Probleme. 3-phasiges Laden habe ich noch nicht probiert. Aber das nutzt Dir ja nichts, wenn ich keine Probleme habe ;)

**Comment by kaeferfreund** [comment]
Eine merkwürdige Sache ist mir noch aufgefallen: 

Alles hat damit angefangen, dass die API als Momentanverbrauchswert 1 W zurück obwohl kein Fahrzeug angeschlossen ist. Als Eigenverbrauch der Box erscheint mir das zu niedrig und nach dem Neustart zeigt die Box wieder 0W an...

Dieses Phänomen ist mir bereits mehrfach aufgefallen, damit scheint sich ein Absturz anzukündigen.

**Comment by peterpoetzi** [comment]
Hi, da ich denke dass es sich hier nur um ein Problem mit einer Box handelt, denke ich dass es sinnvoll ist den Support zu kontaktieren @kaeferfreund

**Comment by kaeferfreund** [comment]
Vielen Dank für die schnelle Antwort...

Die Boxen sind mittlerweile ersetzt
