### ISSUE TITLE
ModBus - Verbrauch pro RFID Karte?

### ISSUE THREAD

**Issue by futureweb** [goecharger/go-eCharger-API-v1#91]
Hallo,
gibt es iw. die Möglichkeit den gespeicherten Verbrauch pro RFID Karte über ModBus auszulesen?
Über die API ist es ja möglich, nur leider nichts über ModBus gefunden.
Vielen Dank, lg
Andreas S.

**Comment by ovhelemann** [comment]
Im Release habe ich das jetzt gelesen, jedoch leider in der Dokumentation die Register noch nicht gefunden. 

![Screenshot_20231017-172148](https://github.com/goecharger/go-eCharger-API-v1/assets/49155079/71b67ec3-2395-4c1a-bda5-cfec7445b48e)

**Comment by ovhelemann** [comment]
Der Support teilte mir mit, dass die register im nachfolgenden Link, ganz unten zu finden sind

https://github.com/goecharger/go-eCharger-API-v2/blob/main/modbus-de.md

Vg ovh

**Comment by 0xFEEDC0DE64** [comment]
genau, los gehts ab register 30333 (332)

dürfen wir dieses Ticket als gefixt betrachten?
